// Rewrite the instructions in your own words

/*
-Create a password validator that takes a email from user and determine that the email is valid or missing
some information like the @ or ". dot" so it could validate also remembering that we need to be sure that 
the email has a structure like String1+@+string2+". dot"+String3
making String1=Name, String2=secondleveldomain and String3=topleveldomain
*/


// paste your JS generated by blockly below here

var email, char_, char_2;


email = window.prompt('Enter your Email');
char_ = email.indexOf('@') + 1;
char_2 = email.lastIndexOf('.') + 1;
if (char_ == 0 || char_ == email.length) {
  window.alert('Invalid: Missing the @');
} else if (char_2 == 0 || char_2 < char_) {
  window.alert('Invalid: Missing the dot.');
} else if (char_ < char_2) {
  window.alert('Valid Email');
}