

/*
we want to create a program that ask for a sentence and provide with a acronym 

-input.. small sentence from user to promot at the time that start running
-output..provide the first letter of each word uppercase and print a acronym

 set a variable to store sentence--
 transform each word the first letter into uppercase--
 remove the rest of the lenght of the work after keep the first one--
 print this letters uppercase in form of acronym */



// paste your JS generated by blockly below here

var result, acro, item;

function textToTitleCase(str) {
  return str.replace(/\S+/g,
      function(txt) {return txt[0].toUpperCase() + txt.substring(1).toLowerCase();});
}


result = '';
acro = window.prompt('Enter you phrase');
acro = textToTitleCase(acro);
acro = acro.split(' ');
for (var item_index in acro) {
  item = acro[item_index];
  result += String(item.charAt(0));
}
window.alert(result);